### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by rnorth** [cristianrgreco/testcontainers-node#1]
Hi @cristianrgreco !

We noticed that you've created this project - it's very nice that you've decided to bring the Testcontainers concept to Node 😄 

A NodeJS implementation was something that I've wanted to do at some point but didn't get around to yet. As you've made a start, would it be possible for us to work together to develop, maintain and publicise this?

Perhaps we could discuss here or on the [Testcontainers Slack team](http://slack.testcontainers.org/)? 

Thanks!
Richard

**Comment by cristianrgreco** [comment]
Hi @rnorth 

Joining forces would be great! I used testcontainers for Java extensively at my last workplace and definitely feel like there's a gap missing for NodeJS.

I've joined the Slack team 😄
